### ISSUE TITLE
App doesn't build after installing ember-x-editable

### ISSUE THREAD

**Issue by dwickern** [shipshapecode/ember-x-editable#59]
After running `ember install ember-x-editable`, `ember serve` gives me this error:
```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/dwickern/code/express/ui/tmp/source_map_concat-input_base_path-blcr9UGe.tmp/0/bower_components/bower-webfontloader/webfont.js'
    at Object.fs.statSync (fs.js:898:18)
    at Concat.keyForFile (/Users/dwickern/code/express/ui/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/Users/dwickern/code/express/ui/node_modules/broccoli-caching-writer/index.js:109:65)
    at /Users/dwickern/code/express/ui/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/Users/dwickern/code/express/ui/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at Concat.CachingWriter [as constructor] (/Users/dwickern/code/express/ui/node_modules/broccoli-caching-writer/index.js:18:10)
    at new Concat (/Users/dwickern/code/express/ui/node_modules/broccoli-concat/concat.js:32:17)
    at module.exports (/Users/dwickern/code/express/ui/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/dwickern/code/express/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:348:10)
    at EmberApp.javascript (/Users/dwickern/code/express/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1214:12)
    at EmberApp.toArray (/Users/dwickern/code/express/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/Users/dwickern/code/express/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/dwickern/code/express/ui/ember-cli-build.js:115:14)
    at Class.setupBroccoliBuilder (/Users/dwickern/code/express/ui/node_modules/ember-cli/lib/models/builder.js:54:19)

```

**Comment by rwwagner90** [comment]
@dwickern what version of ember and ember-cli?

**Comment by rwwagner90** [comment]
@dwickern I made some tweaks, but not sure if it will make a difference. Can you please try 0.3.2 and see if the problem persists? Please let me know your ember and ember-cli versions as well.

**Comment by dwickern** [comment]
@rwwagner90 I'm on ember-cli 2.6.2 with ember 2.9.0.

I don't have a `bower_components/bower-webfontloader` after installing and my `bower.json` does not get modified at all.

**Comment by rwwagner90** [comment]
@dwickern it seems my blueprints were completely incorrect. I think I fixed it now, hopefully, can you please try again on 0.4.0?

**Comment by dwickern** [comment]
@rwwagner90 now I get this error when I try to install:
```
installing ember-x-editable
packages.map is not a function
TypeError: packages.map is not a function
    at Class.addBowerPackagesToProject (/Users/dwickern/code/express/ui/node_modules/ember-cli/lib/models/blueprint.js:1035:44)
    at Class.afterInstall (/Users/dwickern/code/express/ui/node_modules/ember-x-editable/blueprints/ember-x-editable/index.js:11:17)
    at tryCatch (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/dwickern/code/express/ui/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rwwagner90** [comment]
@dwickern ah, the docs on addAddonsToProject vs addBowerPackagesToProject are not consistent. Please try 0.4.1 now. We'll get this working 😄

**Comment by dwickern** [comment]
It builds! Thanks! 🎉

**Comment by rwwagner90** [comment]
@dwickern no problem! If you are using this addon, and need more of the features of x-editable, I would be glad to work with you to implement them 😄
